micronaut:
  server:
    cors:
      enabled: true
  application:
    name: ontology-service-${ONTOLOGY:unknown}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /${api-url.prefix}/${ontology}/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /${api-url.prefix}/${ontology}/docs/**
  serde:
    serialization:
      inclusion: ALWAYS
endpoints:
  all:
    path: /${api-url.prefix}/${ontology}/
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'org.jacksonlaboratory.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
jackson:
  serializationInclusion: ALWAYS

api-url:
  prefix: /api
ontology: ${ONTOLOGY:unknown}
load: ${ONTOLOGY_SERVICE_LOAD:true}
international: ${ONTOLOGY_SERVICE_INTERNATIONAL:false}
