micronaut:
  application:
    name: ontology-service-${ONTOLOGY:unknown}
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: MYSQL
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    db-type: mysql
jpa:
  default:
    entity-scan:
      packages: 'org.jacksonlaboratory.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
api-url:
  prefix: /api/v1
ontology: ${ONTOLOGY:unknown}
load: true
international: true

