micronaut:
  application:
    name: ontology-service-${ONTOLOGY:unknown}
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
netty:
  default:
    allocator:
      max-order: 3
api-url:
  prefix: /api/v1
ontology: ${ONTOLOGY:unknown}