name: Cron Supported Ontologies
on:
    workflow_dispatch:
#    schedule:
#        - cron: "*/30 * * * *"

jobs:
    ontologies:
        strategy:
            matrix:
                include:
                    - ontology: "hp"
                      international: true
                      repo: "https://api.github.com/repos/obophenotype/human-phenotype-ontology"

        uses: TheJacksonLaboratory/ontology-service/.github/workflows/ontology-check-trigger.yml@feature/watcher
        with:
            ontology: ${{ matrix.ontology }}
            international: ${{ matrix.international }}
            load: true
            repo: ${{ matrix.repo }}
        secrets: inherit