name: Cron Ontology Service
on:
    schedule:
        - cron: "0 */4 * * *"
jobs:
    ontologies:
        strategy:
            matrix:
                include:
                    - ontology: "hp"
                      international: true
                      repo: "https://api.github.com/repos/obophenotype/human-phenotype-ontology"
                    - ontology: "mondo"
                      international: false
                      repo: "https://api.github.com/repos/monarch-initiative/mondo"
                    - ontology: "maxo"
                      international: false
                      repo: "https://api.github.com/repos/monarch-initiative/maxo"

        uses: TheJacksonLaboratory/ontology-service/.github/workflows/ontology-check-trigger.yml@main
        with:
            ontology: ${{ matrix.ontology }}
            international: ${{ matrix.international }}
            load: true
            repo: ${{ matrix.repo }}
        secrets: inherit
