name: Cron Ontology Service
on:
    schedule:
        - cron: '0 */4 * * *'
    workflow_dispatch:
jobs:
    ontologies:
        strategy:
            matrix:
                include:
                    - ontology: "hp"
                    - ontology: "mp"
            fail-fast: false
        uses: TheJacksonLaboratory/ontology-service/.github/workflows/ontology-check-trigger.yml@main
        with:
            ontology: ${{ matrix.ontology }}
        secrets: inherit
