name: Check for ontology release
on: workflow_dispatch
#  schedule:
#    - cron: "*/10 * * * *"
jobs:
  watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - name: Setup Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Get latest tag_name
        uses: sergeysova/jq-action@v2
        id: tag
        with:
          cmd: "curl https://api.github.com/repos/obophenotype/human-phenotype-ontology/releases/latest | jq -r '.tag_name'"

       - name: Get latest SHA
         uses: sergeysova/jq-action@v2
         id: sha
         with:
           cmd: "curl https://api.github.com/repos/obophenotype/human-phenotype-ontology/git/ref/tags/${{ steps.tag.outputs.value }} | jq -r '.object.sha'"

      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      - name:  Get existing SHA for service
        id: existing
        run:  |
          echo "value=$(gcloud container images list-tags us-east1-docker.pkg.dev/jax-robinson-hpo-01/docker-dev/ontology/ontology-service-hp | head -n 2 | tail -n 1 | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Compare and configure
        run: |
          echo "${steps.sha.outputs.value}"
          echo "${steps.existing.outputs.value}"