name: Check for ontology release
on:
  workflow_dispatch:

env:
  SERVICE_TAG: ''
  SHOULD_LOAD: false
#  schedule:
#    - cron: "*/10 * * * *"
jobs:
  watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - name: Setup Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Get latest tag_name
        uses: sergeysova/jq-action@v2
        id: tag
        with:
          cmd: "curl https://api.github.com/repos/obophenotype/human-phenotype-ontology/releases/latest | jq -r '.tag_name'"

      - name: Get latest SHA
        uses: sergeysova/jq-action@v2
        id: sha
        with:
          cmd: "curl https://api.github.com/repos/obophenotype/human-phenotype-ontology/git/ref/tags/${{ steps.tag.outputs.value }} | jq -r '.object.sha' | cut -c -7"

      - name:  Get existing SHA for service
        id: existing
        run:  |
          EXISTING=$(gcloud container images list-tags us-east1-docker.pkg.dev/jax-robinson-hpo-01/docker-dev/ontology/ontology-service-hp | head -n 2 | tail -n 1 | awk '{print $2}')
          echo "::set-output name=value::$EXISTING"

      - name: Compare and configure
        run: |
          export SHOULD_LOAD=$("${{steps.sha.outputs.value}}" == "${{steps.existing.outputs.value}}"
          export SERVICE_TAG="${{steps.sha.outputs.value}}"
          echo $SHOULD_LOAD
          echo $SERVICE_TAG